# Generated by Django 6.0.1 on 2026-02-19 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0004_todo_created_at_todo_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="user",
        ),
    ]
