# Generated by Django 6.0.1 on 2026-02-12 22:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_todo_user_alter_todo_description_alter_todo_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="todo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
